# Esoterica

This is a collection of counter-intuitive or otherwise obscure trivia
about the behavior of Scheme implementations and the interpretation of
Scheme standards.

## Different lambdas may return the same procedure

`(eq? (lambda (x) x) (lambda (x) x))` can be either true of false.

## Hoisting `let` outside `define` does not work

This procedure works as expected:

-----
(define (foo)
  (let ((x 1))
    x))
-----

Hoisting the `let` outside the `define`, the code no longer compiles:

-----
(let ((x 1))
  (define (foo)
    x))
-----

The reason is that `foo` is now defined in the scope inside `let`, not
in the scope outside the `let` as it was before. A `let` body cannot
contain only definitions.

Compare with `lambda` which does not deal with definitions, so
hoisting a `let` over a `lambda` works fine:

-----
(define foo
  (lambda ()
    (let ((x 1))
      x)))

(define foo
  (let ((x 1))
    (lambda ()
      x)))
-----

Common Lisp does not support inner definitions, so hoisting a `let`
over a definition works there:

-----
(defun foo ()
  (let ((x 1))
    x))

(let ((x 1))
  (defun foo ()
    x))
-----
